### ISSUE TITLE
ARIA alert informing screen reader users of content flowing outside view is not working

### ISSUE THREAD

**Issue by mcking65** [facebookincubator/exerslide#14]
I just made a presentation that had some slides with too much content for the screen, but the built presentation didn't alert me to it ... like it used to do. For example, this slide has no alert:
https://mcking65.github.io/using-aria1.1-oct2016/#/2

**Comment by fkling** [comment]
I'll look into it!

**Comment by fkling** [comment]
This was finally fixed in db5230111360eb82c41fdc2fc2be20a6ebe702cf and v1.1.5 was released!
