### ISSUE TITLE
Can't make it working

### ISSUE THREAD

**Issue by cristian-sima** [facebookincubator/exerslide#16]
Os: Windows 10 x64 Pro
Node: v6.3.1

I created a new Github project, created a folder `myPresentation` then run the code:

![image](https://cloud.githubusercontent.com/assets/12199042/22065190/c0e94416-dd8f-11e6-9d64-2bb3b2928f5e.png)

**Comment by fkling** [comment]
It works fine on my Mac, so I can only assume this is a general Windows compatibility issue. Please see #8. Sorry for that! I appreciate any help solving this issue!
