### ISSUE TITLE
Ability to write assertions in separate JS file

### ISSUE THREAD

**Issue by BlakeTurner** [facebookincubator/exerslide#17]
First off: this is a really interesting project. Great work!

Re: the JavaScriptExercise layout

I'm wondering if it would be possible for the slide to include an external JS file instead of requiring that assertions be written in the front matter. Maybe a specific path/naming convention would make this easier to achieve?

The use-case is that we'd like to be able to write the assertions and also optionally fire off analytics events on success/fail. That way we can track the success of any given lesson.

Thanks!

**Comment by fkling** [comment]
Hey Blake! I'm glad you like exerslide 😃 

One thing you can do is use the [`atRequireExpansion` transform](https://github.com/facebookincubator/exerslide/blob/4ccb505693cf400686e232ed1919e974eece78eb/packages/exerslide/lib/slide_transforms/atRequireExpansion.js) in `webpack.config.js` ([example](https://github.com/facebookincubator/exerslide/blob/4ccb505693cf400686e232ed1919e974eece78eb/example/webpack.config.js#L127)) and in the slide do

```
---
layout_data:
  assertion: @require('!!raw!path/to/file/')
---
```

That should include the content of `path/to/file/` as a string (I believe I have done this before, but you should try and see whether it really works), just as if you had written the content of the file in the slide.

Is that what you are looking for?

**Comment by BlakeTurner** [comment]
That is awesome. Thanks!

**Comment by fkling** [comment]
I assume this resolved then?
