### ISSUE TITLE
Site breaks when navigating back to it

### ISSUE THREAD

**Issue by Daniel15** [facebookincubator/exerslide#2]
Definitely an edge case, but I figured I'd report it anyways.

Steps to repro:
1. Open new browser tab and go to https://facebookincubator.github.io/exerslide/. Notice that it loads fine
2. Load a different site in the same tab
3. Click the browser Back button to go back to the Exerslide site

Notice that it shows a loading indicator forever:
![](http://ss.dan.cx/2016/08/chrome_31-15.28.35.png)

Chrome 52.0.2743.116 on Windows 10

**Comment by fkling** [comment]
Couldn't repro yet but will look into it. Thanks!

**Comment by Daniel15** [comment]
I can't repro any more... Very strange. I'll keep this open for a day or so in case I encounter it again, but otherwise I guess we can just close it out.

**Comment by Daniel15** [comment]
Still can't repro again, closing this out for now. Will reopen if I see this again. May have been a bug in an older Chrome version as Chrome auto-updated the same day I opened this task.
